version: '3.9'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: cutecardsdatabase
      MYSQL_PASSWORD: 12345678
    ports:
      - '3306:3306'
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: mysql://root:12345678@mysql:3306/cutecardsdatabase
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
